# Use the official Nginx image as a parent image
FROM nginx:latest

# Copy your custom HTML file into the image
# Assume that you have an 'index.html' file in the same directory as your Dockerfile
COPY html/index.html /usr/share/nginx/html/index.html
